version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "biweekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "esbuild"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "biweekly"
    open-pull-requests-limit: 5
