export const DEFAULT_CONTACTS_WEB_BFF_HOST = "0.0.0.0";
export const DEFAULT_CONTACTS_WEB_BFF_PORT = 4010;
export const DEFAULT_CONTACTS_BACKEND_BASE_URL = "http://127.0.0.1:8010";
export const DEFAULT_CONTACTS_TELEMETRY_COLLECTOR_BASE_URL = "http://127.0.0.1:4321";
export const DEFAULT_CONTACTS_BACKEND_AUTH_SUBJECT = "admin-user";
export const DEFAULT_CONTACTS_BACKEND_AUTH_ROLES = "admin";
