name: Notify Discord on Issue Close

on:
  issues:
    types:
      - closed

permissions:
  contents: read
  issues: read

jobs:
  notify:
    uses: wastingnotime/wnt-tools/.github/workflows/notify-discord-on-issue-close.yml@main
    secrets: inherit
