name: Notify Discord on Issue Open

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: read

jobs:
  notify:
    uses: wastingnotime/wnt-tools/.github/workflows/notify-discord-on-issue-open.yml@main
    secrets: inherit
