name: security scans

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: scan repository secrets
        uses: trufflesecurity/trufflehog@v3.95.3
        with:
          path: .

  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: scan repository config with checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12.3102.0
        with:
          directory: .
          framework: all
          quiet: true
          output_format: cli

  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: scan repository config with trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: config
          format: table
